library(DESeq2)
library(WGCNA)
library(annotables)
library(clusterProfiler)
library(flashClust)
# library(RRHO)
# library(RRHO2)
library(edgeR)
# library(STRINGdb)
# library(msigdbr)

library(readr)
library(splitstackshape)  
library(reshape2)
library(data.table)  
library(compete)
library(steepness)
library(PlayerRatings)
library(gridExtra)
library(ineq)
library(cluster)
library(factoextra)
library(Perc)
# library(stringr)
library(brms)
library(coda)
library(flexclust)
library(broom)
library(multcomp)
library(bayesplot)
library(igraph)
library(ggthemes)
library(ggrepel)
library(ggridges)
library(ggnetwork)
library(RColorBrewer)
library(viridis)
library(ggsci)
library(EnhancedVolcano)
library(scales)
library(glue)
library(qwraps2)
library(lubridate)
library(cowplot)
library(tidybayes)
library(tidyverse)

grcm38 <- grcm38 %>% 
  mutate(description = gsub("\\[.*?\\]",'',description)) %>% # to shorten description with better readability
  mutate(symbol = replace(symbol, symbol == 'Gm21320','Mup22')) #apparently it's synonyms and we would like to call it Mups 
